# Course Exemptions {#exemptions}

There are four 400-level courses that are typically part of the MA core that students with some prior study of these areas may wish to be exempted from. Note that an exemption does not give you credit for the class; you must still fulfill the minimum credit requirements for the degree. Courses for which exemptions are offered include:

-   Ling 410: Articulatory Phonetics
-   Ling 420: Morphology
-   Ling 421: Introduction to Phonological Analysis
-   Ling 422: Introduction to Grammatical Analysis

If you wish to seek exemption from any of the courses listed above, you must meet during orientation week (week prior to the start of classes) with the faculty member in charge of exemption for the course, usually the most recent instructor of the course. During this meeting you must provide the instructor with the syllabus from your prior course, and be prepared to discuss course content and possibly be quizzed on course materials. The instructor will then decide to take one of the following options:

(a) exempt you from the class, or

(b) not exempt you from the class, or

(c) require you to take an exemption exam for the course (in this case a minimum passing grade is B (not B-)), or

(d) require you to audit the entire class or a portion of the class; the instructor will inform you of requirements for a successful audit.

Exemption exams, if deemed required by the instructor, are held during the week prior to the first day of instruction and are scheduled in two hour blocks. If you are required to take one or more of these exams, you must notify the Department administrator (linguist [at] hawaii.edu) no later than two weeks prior to the start of classes, stating which exams you are planning to take. The administrator will then notify you of the exam schedule. All exemption exams must be completed no later than Wednesday of the first week of classes. If you are required to take the exemption exam you should attend the course until your exam has been graded and an exemption has been granted.

Instructors must provide exemption documentation or exam grades to the Graduate Chair and relevant students no later than the day before the last day to add classes. You may take any given exemption exam only once. Should you not pass an exam, you must take the relevant course at the first availability, i.e., the same semester if the course is offered (if not, the following semester).

If you intend to seek exemption(s), you must make every effort to do so within the first year of your program.
