# Funding {#funding}

## Departmental Funding

Our primary form of funding for MA students is an **Achievement Scholarship** known as a tuition waiver. In order to be eligible for this, you need to be registered for a minimum of eight (8) credits in the Department of Linguistics.^[Exceptions may be approved by the graduate chair in cases where courses outside the department are an integral part of the student’s program.]

Our primary form of funding for PhD students consists of a **Graduate Assistantship**. A student receiving a GAship needs to register for at least six (6) credits in the Department of Linguistics.

: *With approval of the Graduate Chair, courses outside the department may count toward minum credit requirements, provided the courses are an integral part of the student's degree program.* 


Information about Graduate Assistantships and Achievement Scholarships can be found on the [department website](http://ling.hawaii.edu/degree-programs/funding/).



Towards the end of each semester, the Graduate Chair will distribute a funding report form which all continuing students are required to complete and return by the stated deadline. This form asks for your funding request, eligibility for department tuition support, and other information relevant to assigning financial support for the next semester. Filling out this report is obligatory for all students, and especially important for those seeking (or expecting) financial support from the department. Meeting with your advisor is not required, but you can meet with the Graduate Chair if you need help to complete the form.


## Bilinski

The [Bilinski Fellowship](http://ling.hawaii.edu/degree-programs/funding/bilinski/) provides two types of awards for PhD students:

- The __Dissertation Fellowship__ provides $15,000 per semester for up to three semesters to support ABD student during the dissertation writing phase of their studies.

- The __Pre-Dissertation Research Award__ provides up to $5000 to support data collection and fieldwork. 

Applicants must meet US Citizenship/Residency requirements. More details on the Bilinski awards, and how to apply can be found [here](http://ling.hawaii.edu/degree-programs/funding/bilinski/).

## Extramural Funding

Occasionally faculty may bring in extra funding for GAships, above and beyond the department’s normal GA allotment. These GAships could be full or half positions based on the needs of the position. Credit requirements for all GAships (i.e., department/extra funding and full/half positions) are the same as described above.




