# Additional Requirements

## Language Requirement

All graduate students (MA and PhD) must demonstrate competence in one language other than their native language. PhD students must complete this requirement before advancing to candidacy (i.e., before the dissertation proposal defense).

You can demonstrate your language competence in one of three ways:

1.  Pass a reading/translation test.
2.  Pass a fourth semester language course (e.g., Japanese 202) with a grade of at least B. Courses taken at another university, if you provide transcripts, can fulfill this requirement.
3.  Take a placement test to demonstrate comparable knowledge.

**Please note the following:**

-   You may use English to satisfy the language requirement if it is not your native tongue; certification by the English Language Institute that you are exempt from ELI courses suffices to establish knowledge of English for this purpose. See the department secretary if you qualify to use English to meet your language requirement.
-   Samples of the reading/translation tests administered by the Department of Linguistics are available to check-out from the department office.
-   For French, German, Russian and Spanish, students may opt for the Graduate School Foreign Language Tests (GSFLT), provided they pay the exam fee.
-   Placement tests in languages taught at the University of Hawai'i are usually scheduled just prior to the beginning of the semester. Consult the relevant language department for information.

## Departmental Service {#service}

Voluntary (non-compensated) service to the department is an important part of departmental citizenship. Engaging with departmental organizations provides a more holistic view of the field of linguistics and prepares you for future jobs in the academic, public and private sectors. "Non-compensated" in this context means that you do not receive remuneration in the form of salary or course credit. 

All PhD students are expected to devote at least two academic years to non-compensated service in a departmental organization, such as the following or another approved by the Graduate Chair.

- [departmental reading group](https://manoa.hawaii.edu/linguistics/research-reading-groups/) (e.g. Austronesian Circle, EATS, LARG)
- [Language Documentation Training Center](http://ldtc.org)
- Linguistic Society of Mānoa

One of your years of service should be as a participant and another in a leadership role (e.g. reading group organizer, LSM officer)





## Archiving Research Data  {#archiving}

Students whose thesis or dissertations are based on data collected during the course of their own research are encouraged to properly archive their data in an appropriate language archive or data repository in order to ensure the longevity of the data and facilitate reproducible research. Students whose research relies on documentary corpora are required to archive their data prior to graduation. Students will develop an archiving plan early and will include a description of this plan in the [Dissertation Proposal] (or combined Proposal/Prospectus). Data can be archived with one of the following repositories, or with another archive approved by your advisor.

-   [Kaipuleohone](https://hdl.handle.net/10125/4250), the University of Hawai'i Digital Language Archive
-   another [DELAMAN](http://www.delaman.org) archive
-   [Zenodo](http://zenodo.org)
-   [TROLLing](https://trolling.uit.no/)
-   [OSF](http:/osf.io)

For students archiving their data in Kaipuleohone, the archiving plan should be developed in consultation with the current archive director. All students will be required to submit proof of deposit in writing from the archive director to the committee before the dissertation can be approved.

In addition, each student is required to cite data in the thesis or dissertation coming from his or her own archived materials via a persistent identifier URL to the source file in the archive. The exact format of the citation and the level of granularity (e.g., timecode in an audio file; collection of files; dataset; etc.) can be developed in consultation with the dissertation advisor, and should reflect the best practices in the student's linguistic subfield. See the [Austin Principles of Data Citation in Linguistics](https://site.uit.no/linguisticsdatacitation/) for more information.

## Adequate Writing Skills {#writing}

Adequate writing skills are crucial to the completion of the PhD degree. Students must be able to present their ideas in writing in a manner that meets the standards of professional journals in the field of study.

Criteria for successful academic writing include the following:

-   The student is able to organize her/his thoughts in a logical and coherent way.
-   The main goal is clearly stated at the beginning and returned to at the end.
-   Claims are clearly stated and explained.
-   There are clear subsections (e.g. introduction. background, data, results, discussion and conclusions).
-   Technical terms are defined appropriately for the intended audience
-   Every generalization is supported by evidence.
-   Adequate and relevant examples are given.
-   Adequate references are given.
-   Concluding statements follow clearly from what has been presented.
-   The document has been spell-checked.
-   The documebnt is written in grammatical English.

Students' writing skills are discussed by the faculty in the annual student review. While there is no formal writing requirement, students whose writing skills are deemed inadequate may be required to enroll in a writing course from the following list. Students can also schedule appointments with the Manoa Writing Center.


```{r, echo=F}
writing <- read.csv('writing.csv')
knitr::kable(writing, booktabs=T, caption="Writing Courses")
```
