# Masters-to-PhD Transition

This chapter provides information for current MA students seeking to apply to the PhD program at the UHM Department of Linguistics.

## Overview
Like other PhD programs around the country, we have a limited number of openings for our PhD program and must be highly selective in our admissions decisions. Current MA students are not guaranteed admission into the PhD program, but must get approval from the Admissions Committee through a process that is similar to, but not identical to, applying as an external applicant. 

Applying as an internal applicant – that is, applying before your MA has been awarded -- has a few benefits over applying as an external applicant. The credits you have already earned will count toward your PhD, and the application process requires fewer documents; furthermore you will only need to pay the UH application fee  if your application is successful. However, you will not earn your MA degree immediately, but can instead request the MA degree later, once you have advanced to doctoral candidacy (i.e. achieved All-But-Dissertation status).

## Some considerations
Historically, we admit roughly 15% of external applications, and 30% of internal applications. The merit of each application - internal or external - is evaluated using the same criteria, with the strongest candidates selected from among all applications.

We have developed a list of criteria for admission to our PhD program and some self-evaluation questions you should consider carefully if you are thinking about applying. You should ask yourself these questions on a regular basis, and if you are in doubt about your answers, you may not be ready to embark on a PhD.

Criterion | Self-evaluation questions
----------|---------------------------
A record of academic accomplishment as reflected in outstanding work in previous linguistics courses | Have any of my professors suggested I go on to PhD? How many? Have my grades been very strong?
A match between the interests of the student and the strengths of the faculty | Does the Department currently have faculty who are willing and able to support the kind of research I hope to do? Has a particular professor expressed an interest in supervising my independent research?
Analytic (problem-solving) skills |  Have I demonstrated my skill at analyzing linguistic data and critically evaluating hypotheses proposed to explain the workings of language?
Evidence of an ability to work independently and to think critically | 
Can I think critically and work independently with minimal direction?
Writing ability | Can I express myself clearly in writing in single-authored papers?
Oral communication | Do I speak out in class or in Tuesday Seminars, asking incisive questions and offering novel insights?
Professional participation and departmental good-citizenship | Have I made any conference, seminar or reading group presentations? Have I shown myself to be a cooperative colleague through participation in departmental activities? Have I met with all the professors in the department?

## Application
Once you decide to apply, the first step is to submit the following documents to the Linguistics Department for review by the Admissions Committee:
- A detailed Statement of Purpose describing your research interests and how you think you are qualified for PhD work in our department
- A writing sample that best demonstrates your ability to communicate about linguistics in writing (e.g. a successful term paper)

Letters of reference are not necessary, nor are updated test scores and transcripts. In lieu of letters, the full faculty will be polled as to your suitability for transfer to the PhD program, with comments solicited and potential advisors sought. The Admissions Committee considers the results from this poll, as well as the Statement of Purpose, writing sample and any other information available to the committee.

Deadlines: We accept applications for Spring transfer (deadline September 1st of the preceding year) and Fall transfer (deadline the preceding January 1st), although you are strongly advised to apply in the Fall semester (January 1st deadline). Furthermore, you are strongly advised to wait until your second year before applying. Any internal candidate who applies and is rejected is welcome to ask the Graduate Chair for advice on improving the application for a future round.

## Acceptance
Upon successful acceptance into the PhD program by the Admissions Committee, you must [apply to the Graduate Division](http://www.apply.hawaii.edu) and select “Change in Graduate Program.” You will need to pay an application fee.

Important Note: If you apply for graduation while you are in the MA program, you need to use the Application for Admission to a Doctorate in the Same Discipline. We therefore urge you not to apply for graduation until you know you are leaving UH for certain.

A common scenario is the following: a student applies to the PhD program in December. The deadline to apply for graduation (from the MA program) is in February, but the student will not learn of the outcome of their application to the PhD program until March or April. The student therefore applies for graduation, just to be safe. If they are offered a position in the PhD program, they will now have to complete a full university application, since the university sees this student as having a terminal MA degree at the time of entrance into the PhD program. We therefore recommend that unless you are certain you will be leaving UH, that you not apply for graduation while an application to our PhD program is pending. If your application to the PhD program is unsuccessful, you may file a late petition for graduation. The only penalty for a late petition for graduation is that you will not have your name listed in the official graduation handbook.

