# Dissertation Proposal and Prospectus {#prospectus}

In order to advance to candidacy, you must prepare and successfully defend a dissertation proposal and prospectus.
The dissertation proposal is a requirement of Graduate Division, while the dissertation prospectus is a requirement of the Department of Linguistics. You can choose to submit and defend these separately, but the more time-efficient option is to combine the two milestones into one document and defense (see [Combining the Dissertation Proposal and Dissertation Prospectus]).

## Dissertation Proposal
The dissertation proposal should include:

1. a clear statement of the topic of the dissertation
2. a clear statement of the research questions to be investigated in the dissertation and why they are worth addressing (including a brief synopsis of the relevant literature)
3. a clear statement of the methodology to be employed for the investigation of those research questions
4. A data archiving plan (see [Archiving Fieldwork Data])
5. evidence of approval from the [Institutional Review Board](#IRB) (IRB) to carry out research involving human subjects (if called for)
6. a tentative timetable for completion of the dissertation.

In general, it is expected that a proposal will be from 5 to 10 pages in length (double spaced); once defended and approved by your dissertation committee, your proposal must be submitted to the department and will be available to other students in perpetuity.

When you are preparing your dissertation proposal, it is time to enlist an ‘outside member’ for your committee. (See [Forming a Dissertation Committee] below) Your dissertation proposal must be approved at a defense attended by ALL members of your dissertation committee or their proxies, in accordance with Graduate Division Rules.

Upon successful defense of the dissertation proposal, you are officially admitted to candidacy for the PhD degree and are considered to a "PhD candidate."

## Dissertation Prospectus
The dissertation prospectus fulfills the function of the former dissertation proposal, numerous examples of which are available from the department office. It should contain a DETAILED discussion of the research questions and research methods (including experiments, if appropriate) that will be pursued in the dissertation, a review of the relevant literature, and results from pilot studies. In general, a dissertation prospectus will be from 30 to 50 pages in length (double spaced); once defended and approved by your dissertation committee, the prospectus must be submitted to the department and will be in the public domain. You are encouraged to examine examples available in the department office.

Your dissertation prospectus must be approved at a defense attended by members of your dissertation committee or their proxies. Because the prospectus is a departmental requirement rather than a Graduate Division requirement, the external member (University Representative) on your committee need not attend, if this meets with the approval of your committee chair.

## Forming a Dissertation Committee
Throughout the early years of the program, you should talk to as many faculty members as possible about your interests so that you can decide who would be the best members of your Dissertation Committee. Your committee, and especially your committee chair, will guide you through the preparation of your dissertation. Once you have a general topic in mind for your dissertation, ask faculty members if they are willing to be on your committee, and then let the department office know when you have a committee to propose.

A dissertation committee must meet the following requirements:

- Must consist of at least five members, including the University Representative. (A committee usually contains no more than six members.) The initial advisory committee will have at least four.
- At least two members must be faculty members in the Department of Linguistics.
- At least one other member should either be a member of the department or a member of the  department's [Cooperating Faculty](http://manoa.hawaii.edu/linguistics/people/). Occasionally, with the permission of the Graduate Chair and the Dean of Graduate Studies, a committee can include a faculty member at another university. This may be appropriate when the dissertation topic lies outside the areas of core expertise of UHM faculty.  
- The committee chair (principal advisor and dissertation supervisor) must be chosen a Department of Linguistics or, with the permission of the Graduate Chair, a member of from the  department's [Cooperating Faculty](http://manoa.hawaii.edu/linguistics/people/). (With prior approval, it is possible to have two co-chairs.)
- In addition, the committee chair must be a member of the university's [Graduate Faculty](http://manoa.hawaii.edu/graduate/content/select-committee-member). This typically includes all faculty with the rank of Assistant Professor or above. 
- Your committee must be approved by the Graduate Chair. The Graduate Chair will ask you about your committee member preferences and will advise you on potential members if necessary.
- Must include a _University Representative_, a member of the university's [Graduate Faculty](http://manoa.hawaii.edu/graduate/content/select-committee-member) who is neither a member of the Department of Linguistics nor a member of the department's Cooperating Faculty. 


### University Representative {-}
The University Representative's function is to ensure that the department properly follows the procedures mandated by Graduate Division, and that each student is treated fairly. Although a particular faculty member may be listed on the Graduate Division’s list of possible University Representatives, the Linguistics Graduate Chair must approve all committee members on a case-by-case basis in order to ensure that the University Representative not be too close to linguistics to function as an unbiased outsider. That said,  faculty from outside departments can often provide constructive input on the content of your dissertation, so it is wise to discuss your choice of University Representative with your advisor and the Graduate Chair. 




## Combining the Dissertation Proposal and Dissertation Prospectus
If you wish to bypass the dissertation proposal, and simply submit a dissertation prospectus that meets both sets of requirements, you may do so provided that you receive prior approval from your committee chair. In this case, you must notify the department office so that they can inform Graduate Division that you have satisfied the dissertation proposal requirement and record that you have met the proposal and prospectus requirements.

Be sure to consult your committee chair about his/her expectations on what s/he expects in your proposal and prospectus.

Many students have found it helpful to ground the details of their proposal on preliminary research done for a course project, a Working Paper, a seminar project, or other pilot study.

The department office needs a copy of your IRB human subjects’ approval/exemption. Submit this to the department office shortly after your proposal defense because it needs to be submitted with a form to Graduate Division for processing.

You will then be allowed to register for LING 800. Please note, however, that it takes 10 days after the final, approved version of the dissertation proposal has been submitted for the departmental staff to do the paperwork necessary to permit registration in LING 800. Students are advised that they must leave adequate time between the dissertation proposal defense and the deadline for registration to make any required revisions and to permit the office staff to do the needed paperwork.

Once your dissertation proposal has been approved by your committee, you must submit an approved copy (with your committee chair’s signature on the first page acknowledging that all revisions have been made) to the department office no later than the end of the semester following your proposal defense. This copy will be available to all faculty and PhD students in the Linguistics Department. Your All-But-Dissertation (ABD) Certificate will be given to you after the department receives a copy of your approved proposal.

Similar to your proposal, a printed copy of your approved dissertation prospectus must also be submitted to the department office no later than the end of the semester following your prospectus defense.


